import { Container, Grid } from "@mui/material";
import Head from "next/head";
import data from "../../JSON/serverData.json"
import { renderComponent } from "../../lib/render-component";
import React from "react";

export default function Page(props: any) {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component={"main"} maxWidth={"xl"} sx={{ padding: 0 }}>
        {props?.pageData?.map((obj: any) => {
          return (
            <Grid key={obj?.type} mt={1} mb={2}>
              {renderComponent(obj)}
            </Grid>
          )
        })}
      </Container>
    </>
  );
}

export async function getStaticProps(context: any) {
  const fetchedData: any = data?.homepage?.data?.components
  if (fetchedData == null || fetchedData?.length < 1) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      pageData: fetchedData
    },
  };
}

